version: '3'
services:
  postgresdb:
    image: postgres:alpine3.17
    container_name: postgresqldb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=probucketool
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - probucketool

  probucket_backend:
    container_name: pro_tool_backend
    build: /backend
    ports:
      - 9025:8080
    depends_on:
      - postgresdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/pro_bucket_tool
      - SPRING_DATASOURCE_USERNAME=probucketool
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - probucketool

  probucket_frontend:
    container_name: pro_tool_frontend
    build: /frontend
    ports:
      - 3000:80


volumes:
  postgres-data:
    driver: local

networks:
  probucketool: