export const SET_ERRORS = "SET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_ALL_PROJECTS = "SET_ALL_PROJECTS";
export const SET_PROJECT_DETAILS = "SET_PROJECT_DETAILS";

export const SET_TASK_LISTS = "SET_TASK_LISTS";
export const SET_SINGLE_TASK = "SET_SINGLE_TASK";
export const REMOVE_TASK_DETAILS = "REMOVE_TASK_DETAILS";

export const SET_SUBTASK_LIST = "SET_SUBTASK_LIST";
export const SET_SELECTED_SUBTASK = "SET_SELECTED_SUBTASK";

export const SET_TEAM_MEMBER_LIST = "SET_TEAM_MEMBER_LIST";
export const SET_ONE_TEAM_MEMBER = "SET_ONE_TEAM_MEMBER";

export const SET_COMMENT_LIST = "SET_COMMENT_LIST";

export const SET_NOTES_LIST = "SET_NOTES_LIST";
